### PR TITLE
P5 54 create docker image with osek compiler

### PR DESCRIPTION
**Pull request by technight**
# Create docker image with osek compiler

Created dockerfile that will build a docker image that can run the nxtOSEK compiler-tool-chain.
Added a couple of patched files from nxtOSEK that will be used when building the docker image.
Also created a couple of scripts for integrating docker with the build process.
And at last added a simple hello world to the source code.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 08b8c257e11614365ae593628413d120811268ad
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 70ddd8c5acead8159cbfd5942358455343656b14
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 08b8c257e11614365ae593628413d120811268ad
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 70ddd8c5acead8159cbfd5942358455343656b14
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: ec2dc581e310d6f35165cd3df0abefb8b8625855
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 08b8c257e11614365ae593628413d120811268ad
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 70ddd8c5acead8159cbfd5942358455343656b14
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: ec2dc581e310d6f35165cd3df0abefb8b8625855
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: b15e1d321beaaa79412451af3f23b1f7da3f2dba
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 08b8c257e11614365ae593628413d120811268ad
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 70ddd8c5acead8159cbfd5942358455343656b14
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: ec2dc581e310d6f35165cd3df0abefb8b8625855
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: b15e1d321beaaa79412451af3f23b1f7da3f2dba
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 5908ba7582eb268ee75f0987d5cb0cadbaba9453
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 08b8c257e11614365ae593628413d120811268ad
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 70ddd8c5acead8159cbfd5942358455343656b14
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: ec2dc581e310d6f35165cd3df0abefb8b8625855
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: b15e1d321beaaa79412451af3f23b1f7da3f2dba
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 5908ba7582eb268ee75f0987d5cb0cadbaba9453
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 95a310c0ff6b3d9372a55098830632a0708ca1da
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 08b8c257e11614365ae593628413d120811268ad
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 70ddd8c5acead8159cbfd5942358455343656b14
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: ec2dc581e310d6f35165cd3df0abefb8b8625855
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: b15e1d321beaaa79412451af3f23b1f7da3f2dba
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 5908ba7582eb268ee75f0987d5cb0cadbaba9453
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 95a310c0ff6b3d9372a55098830632a0708ca1da
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: f45a2c237968b3998ddc1ba4b7661d7bfdb6f4ca
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 08b8c257e11614365ae593628413d120811268ad
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 70ddd8c5acead8159cbfd5942358455343656b14
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: ec2dc581e310d6f35165cd3df0abefb8b8625855
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: b15e1d321beaaa79412451af3f23b1f7da3f2dba
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 5908ba7582eb268ee75f0987d5cb0cadbaba9453
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 95a310c0ff6b3d9372a55098830632a0708ca1da
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: f45a2c237968b3998ddc1ba4b7661d7bfdb6f4ca
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: df0a589a89b7859871e0059882a486ee7e332962
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 08b8c257e11614365ae593628413d120811268ad
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 70ddd8c5acead8159cbfd5942358455343656b14
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: ec2dc581e310d6f35165cd3df0abefb8b8625855
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: b15e1d321beaaa79412451af3f23b1f7da3f2dba
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 5908ba7582eb268ee75f0987d5cb0cadbaba9453
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 95a310c0ff6b3d9372a55098830632a0708ca1da
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: f45a2c237968b3998ddc1ba4b7661d7bfdb6f4ca
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: df0a589a89b7859871e0059882a486ee7e332962
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by technight** [comment]
Til alle der vil teste :
Prerequisite: hav docker installeret. 
How to: Checkout branch, cd til code/nxt og kør ./build.sh - burde bygge og smide binaries i ./output
Note: første run pukler docker image, så første run gaver RIGTIG lang tid. Efterfølgende byg bør tage få sekunder

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 08b8c257e11614365ae593628413d120811268ad
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 70ddd8c5acead8159cbfd5942358455343656b14
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: ec2dc581e310d6f35165cd3df0abefb8b8625855
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: b15e1d321beaaa79412451af3f23b1f7da3f2dba
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 5908ba7582eb268ee75f0987d5cb0cadbaba9453
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 95a310c0ff6b3d9372a55098830632a0708ca1da
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: f45a2c237968b3998ddc1ba4b7661d7bfdb6f4ca
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: df0a589a89b7859871e0059882a486ee7e332962
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
