### PR TITLE
Fixes: P5-20 - Add Overcommit

### PR DESCRIPTION
**Pull request by frederikspang**
Install Guide 

`gem install overcommit`

`overcommit --install`

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1e49f118715d87fc57469b8ea12cf9d5938ff6d4
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, fixes, adds**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1e49f118715d87fc57469b8ea12cf9d5938ff6d4
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, fixes, adds**

Guidelines are available at https://github.com/aau-hcl-p5/main

---
This message was auto-generated by https://gitcop.com

**Comment by C0DK** [comment]
Tester lige om det virker senere :P men fanme let gjort.

**Comment by technight** [comment]
Nice. Kan du måske tilføje test-report scriptet right away? :smile:

**Pull request merged**
